### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by nagbg** [thyyppa/laravel-filemaker-api#1]
Is there any documentation available?

**Comment by thyyppa** [comment]
Not yet! I pushed this a bit premature because I needed it on packagist asap. I didn't realize there would be any interest, but yeah, I'll totally write up some docs!

Tests will come as well. I'll keep breaking changes out of 0.1.x, but expect some in 0.2.x 1.0.0 will come after docs, test, and some cleanup and hardening.

**Comment by thyyppa** [comment]
Alright, I'm in the process of splitting the Filemaker and Laravel code into two projects as it was kind of a tangled mess.

Right now I have the Filemaker API connector done, which may be of use to you:
https://github.com/thyyppa/fluent-fm

The eloquent model adapter is next on the list.

**Comment by nagbg** [comment]
It looks great. This is just what I need. Great work and thank you so much.
